# Generated by Django 5.1.2 on 2025-11-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='solicitudes/'),
        ),
        migrations.AlterField(
            model_name='testimonioestudiante',
            name='anio',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
