# Generated by Django 5.1.2 on 2025-12-05 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_enrollmentrequest_pdf_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_matricula', to='api.programa')),
            ],
        ),
    ]
